In [2]:
import pandas as pd

In [3]:
sales_data = pd.DataFrame({
    'product': ['노트북', '마우스', '키보드', '모니터', '스피커'],
    'price': [1200000, 25000, 80000, 350000, 120000],
    'quantity': [10, 50, 30, 15, 25],
    'category': ['전자제품', '주변기기', '주변기기', '전자제품', '주변기기']
})

sales_data

  product    price  quantity category
0     노트북  1200000        10     전자제품
1     마우스    25000        50     주변기기
2     키보드    80000        30     주변기기
3     모니터   350000        15     전자제품
4     스피커   120000        25     주변기기

In [4]:
product_series = sales_data['product']
product_series

0    노트북
1    마우스
2    키보드
3    모니터
4    스피커
Name: product, dtype: str

In [5]:
price_quantity = sales_data[['product', 'price', 'quantity']]
price_quantity

  product    price  quantity
0     노트북  1200000        10
1     마우스    25000        50
2     키보드    80000        30
3     모니터   350000        15
4     스피커   120000        25

In [6]:
first_three = sales_data[0:3]
first_three

  product    price  quantity category
0     노트북  1200000        10     전자제품
1     마우스    25000        50     주변기기
2     키보드    80000        30     주변기기

In [7]:
expensive_products = sales_data[sales_data['price'] >= 100000]
expensive_products

  product    price  quantity category
0     노트북  1200000        10     전자제품
3     모니터   350000        15     전자제품
4     스피커   120000        25     주변기기

In [8]:
high_quantity = sales_data.query('quantity > 20')
high_quantity

  product   price  quantity category
1     마우스   25000        50     주변기기
2     키보드   80000        30     주변기기
4     스피커  120000        25     주변기기

In [9]:
sales_data_indexed = sales_data.set_index('product')
print(sales_data_indexed)

           price  quantity category
product
노트북      1200000        10     전자제품
마우스        25000        50     주변기기
키보드        80000        30     주변기기
모니터       350000        15     전자제품
스피커       120000        25     주변기기

In [10]:
notebook_info = sales_data_indexed.loc['노트북', 'price']
print(f"노트북 가격: {notebook_info}")

노트북 가격: 1200000

In [11]:
selected_data = sales_data_indexed.loc[['노트북', '모니터'], ['price', 'quantity']]
selected_data

           price  quantity
product
노트북      1200000        10
모니터       350000        15

In [12]:
positional_data = sales_data.iloc[[0, 2], [1, 2]]
positional_data

     price  quantity
0  1200000        10
2    80000        30

In [13]:
filtered_products = sales_data[(sales_data['price'] >= 50000) & (sales_data['quantity'] >= 20)]
print(sales_data)
print(f'\n{filtered_products}')

  product    price  quantity category
0     노트북  1200000        10     전자제품
1     마우스    25000        50     주변기기
2     키보드    80000        30     주변기기
3     모니터   350000        15     전자제품
4     스피커   120000        25     주변기기

  product   price  quantity category
2     키보드   80000        30     주변기기
4     스피커  120000        25     주변기기

In [14]:
electronics_group = sales_data.groupby('category').get_group('전자제품')
print(electronics_group)

  product    price  quantity category
0     노트북  1200000        10     전자제품
3     모니터   350000        15     전자제품

In [16]:
sales_data['category_avg_price'] = sales_data.groupby('category')['price'].transform('mean')
# print(sales_data[['product', 'category', 'price', 'category_avg_price']])
print(sales_data)

  product    price  quantity category  category_avg_price
0     노트북  1200000        10     전자제품            775000.0
1     마우스    25000        50     주변기기             75000.0
2     키보드    80000        30     주변기기             75000.0
3     모니터   350000        15     전자제품            775000.0
4     스피커   120000        25     주변기기             75000.0