In [2]:
import pandas as pd

In [2]:
order_data = pd.DataFrame({
    'order_id': ['ORD001', 'ORD002', 'ORD003', 'ORD004', 'ORD005', 'ORD006', 'ORD007', 'ORD008'],
    'customer_id': ['C001', 'C002', 'C001', 'C003', 'C002', 'C004', 'C001', 'C003'],
    'product_category': ['전자제품', '의류', '전자제품', '도서', '의류', '전자제품', '도서', '의류'],
    'order_amount': [150000, 45000, 320000, 25000, 67000, 89000, 35000, 52000],
    'customer_age': [28, 35, 28, 42, 35, 31, 28, 42],
    'region': ['서울', '부산', '서울', '대구', '부산', '서울', '서울', '대구'],
    'order_date': pd.to_datetime(['2024-01-15', '2024-01-16', '2024-01-18', '2024-01-20',
                                  '2024-01-22', '2024-01-25', '2024-01-28', '2024-01-30'])
})

display(order_data)

,order_id,customer_id,product_category,order_amount,customer_age,region,order_date
0,ORD001,C001,전자제품,150000,28,서울,2024-01-15
1,ORD002,C002,의류,45000,35,부산,2024-01-16
2,ORD003,C001,전자제품,320000,28,서울,2024-01-18
3,ORD004,C003,도서,25000,42,대구,2024-01-20
4,ORD005,C002,의류,67000,35,부산,2024-01-22
5,ORD006,C004,전자제품,89000,31,서울,2024-01-25
6,ORD007,C001,도서,35000,28,서울,2024-01-28
7,ORD008,C003,의류,52000,42,대구,2024-01-30

In [3]:
print("=== 데이터프레임 기본 정보 ===")
print(f"데이터 크기: {order_data.shape}")
print(f"컬럼명: {list(order_data.columns)}")

print("\n=== 데이터 타입 정보 ===")
print(order_data.dtypes)

print("\n=== 기술통계량 ===")
print(order_data.describe())

print("\n=== 카테고리별 주문 빈도 ===")
print(order_data['product_category'].value_counts())

print("\n=== 지역별 분포 ===")
print(order_data['region'].value_counts())

print("\n=== 결측치 확인 ===")
print(order_data.isnull().sum())

=== 데이터프레임 기본 정보 ===
데이터 크기: (8, 7)
컬럼명: ['order_id', 'customer_id', 'product_category', 'order_amount', 'customer_age', 'region', 'order_date']

=== 데이터 타입 정보 ===
order_id                       str
customer_id                    str
product_category               str
order_amount                 int64
customer_age                 int64
region                         str
order_date          datetime64[us]
dtype: object

=== 기술통계량 ===
       order_amount  customer_age           order_date
count       8.00000      8.000000                    8
mean    97875.00000     33.625000  2024-01-21 18:00:00
min     25000.00000     28.000000  2024-01-15 00:00:00
25%     42500.00000     28.000000  2024-01-17 12:00:00
50%     59500.00000     33.000000  2024-01-21 00:00:00
75%    104250.00000     36.750000  2024-01-25 18:00:00
max    320000.00000     42.000000  2024-01-30 00:00:00
std     98018.12879      5.926635                  NaN

=== 카테고리별 주문 빈도 ===
product_category
전자제품    3
의류      3
도서      2
Name: count, dtype: int64

=== 지역별 분포 ===
region
서울    4
부산    2
대구    2
Name: count, dtype: int64

=== 결측치 확인 ===
order_id            0
customer_id         0
product_category    0
order_amount        0
customer_age        0
region              0
order_date          0
dtype: int64

In [4]:
print("\n=== 데이터 타입 정보 ===")
print(order_data.dtypes)

=== 데이터 타입 정보 ===
order_id                       str
customer_id                    str
product_category               str
order_amount                 int64
customer_age                 int64
region                         str
order_date          datetime64[us]
dtype: object

In [5]:
print("\n=== 기술통계량 ===")
print(order_data.describe())

=== 기술통계량 ===
       order_amount  customer_age           order_date
count       8.00000      8.000000                    8
mean    97875.00000     33.625000  2024-01-21 18:00:00
min     25000.00000     28.000000  2024-01-15 00:00:00
25%     42500.00000     28.000000  2024-01-17 12:00:00
50%     59500.00000     33.000000  2024-01-21 00:00:00
75%    104250.00000     36.750000  2024-01-25 18:00:00
max    320000.00000     42.000000  2024-01-30 00:00:00
std     98018.12879      5.926635                  NaN

In [6]:
print("\n=== 카테고리별 주문 빈도 ===")
print(order_data['product_category'].value_counts())

=== 카테고리별 주문 빈도 ===
product_category
전자제품    3
의류      3
도서      2
Name: count, dtype: int64

In [7]:
print("\n=== 지역별 분포 ===")
print(order_data['region'].value_counts())

=== 지역별 분포 ===
region
서울    4
부산    2
대구    2
Name: count, dtype: int64

In [8]:
print("\n=== 결측치 확인 ===")
print(order_data.isnull().sum())

=== 결측치 확인 ===
order_id            0
customer_id         0
product_category    0
order_amount        0
customer_age        0
region              0
order_date          0
dtype: int64

In [9]:
amount_stats = order_data['order_amount'].agg(['mean', 'median', 'std', 'min', 'max', 'count'])

In [10]:
print("=== 주문금액 통계량 ===")
print(amount_stats)

=== 주문금액 통계량 ===
mean       97875.00000
median     59500.00000
std        98018.12879
min        25000.00000
max       320000.00000
count          8.00000
Name: order_amount, dtype: float64

In [12]:
print("\n=== 주문금액 분위수 ===")
quantiles = order_data['order_amount'].quantile([0.25, 0.5, 0.75, 1.0])
print(quantiles)

=== 주문금액 분위수 ===
0.25     42500.0
0.50     59500.0
0.75    104250.0
1.00    320000.0
Name: order_amount, dtype: float64

In [13]:
print("\n=== 수치형 변수 간 상관관계 ===")
numeric_corr = order_data[['customer_age', 'order_amount']].corr()
print(numeric_corr)

=== 수치형 변수 간 상관관계 ===
              customer_age  order_amount
customer_age      1.000000     -0.559552
order_amount     -0.559552      1.000000

In [14]:
print("\n=== 각 컬럼별 고유값 개수 ===")
print(order_data.nunique())

=== 각 컬럼별 고유값 개수 ===
order_id            8
customer_id         4
product_category    3
order_amount        8
customer_age        4
region              3
order_date          8
dtype: int64

In [15]:
order_data.to_csv('data.csv', index=False, encoding='utf-8')

In [16]:
order_data.to_csv('data.csv', index=False, encoding='utf-8-sig')

In [17]:
region_category_pivot = pd.pivot_table(
    order_data,
    values='order_amount',
    index='region',
    columns='product_category',
    aggfunc='mean',
    fill_value=0
)

In [18]:
print("=== 지역별 카테고리별 평균 주문금액 ===")
print(region_category_pivot)

=== 지역별 카테고리별 평균 주문금액 ===
product_category       도서       의류           전자제품
region
대구                25000.0  52000.0       0.000000
부산                    0.0  56000.0       0.000000
서울                35000.0      0.0  186333.333333

In [19]:
multi_agg_pivot = pd.pivot_table(
    order_data,
    values='order_amount',
    index='region',
    columns='product_category',
    aggfunc=['mean', 'count', 'sum'],
    fill_value=0,
    margins=True  # 총합 행/열 추가
)

print("=== 다중 집계 함수 피봇테이블 (일부) ===")
print(multi_agg_pivot['mean'])

=== 다중 집계 함수 피봇테이블 (일부) ===
product_category       도서            의류           전자제품       All
region
대구                25000.0  52000.000000       0.000000   38500.0
부산                    0.0  56000.000000       0.000000   56000.0
서울                35000.0      0.000000  186333.333333  148500.0
All               30000.0  54666.666667  186333.333333   97875.0

In [20]:
order_data['age_group'] = pd.cut(order_data['customer_age'],
                                 bins=[0, 30, 40, 50],
                                 labels=['20대', '30대', '40대'])
print(order_data['age_group'])

0    20대
1    30대
2    20대
3    40대
4    30대
5    30대
6    20대
7    40대
Name: age_group, dtype: category
Categories (3, str): ['20대' < '30대' < '40대']

In [21]:
age_region_pivot = pd.pivot_table(
    order_data,
    values='order_id',
    index='age_group',
    columns='region',
    aggfunc='count',
    fill_value=0
)
print("=== 연령대별 지역별 주문 건수 ===")
print(age_region_pivot)

=== 연령대별 지역별 주문 건수 ===
region     대구  부산  서울
age_group
20대         0   0   3
30대         0   2   1
40대         2   0   0

In [23]:
customer_stats = order_data.groupby('customer_id').agg({
    'order_amount': ['count', 'sum', 'mean', 'max'],
    'order_id': 'count'
}).round(2)

display(customer_stats)

            order_amount                            order_id
                   count     sum       mean     max    count
customer_id
C001                   3  505000  168333.33  320000        3
C002                   2  112000   56000.00   67000        2
C003                   2   77000   38500.00   52000        2
C004                   1   89000   89000.00   89000        1

In [ ]:
region_analysis = order_data.groupby()